openapi: 3.0.0
info:
  title: Management Report Dashboard API
  description: API para obtener datos de consumo energético en diferentes períodos
  version: 1.0.0

paths:
  /management/report/dashboard/data:
    get:
      summary: Obtener datos del dashboard de consumo energético
      description: Devuelve los datos de consumo energético para un sitio específico y período determinado.
      parameters:
        - name: period
          in: query
          description: Período de tiempo para el que se solicita la información.
          required: true
          schema:
            type: string
            enum: [this-year, past-year, last-year, this-month, past-month, last-month]
        - name: siteId
          in: query
          description: Identificador del sitio.
          required: true
          schema:
            type: string
      responses:
        200:
          description: Datos de consumo energético obtenidos exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  siteId:
                    type: string
                    description: Identificador del sitio.
                  period:
                    type: string
                    description: Período de tiempo solicitado.
                  status:
                    type: string
                    description: Estado de la respuesta.
                    example: success
                  energyData:
                    type: array
                    description: Datos de consumo energético.
                    items:
                      type: object
                      properties:
                        month:
                          type: string
                          description: Mes en formato abreviado (presente si el período es anual).
                          example: Jan
                        day:
                          type: integer
                          description: Día del mes (presente si el período es mensual).
                          example: 15
                        consumption:
                          type: number
                          format: float
                          description: Consumo energético en kWh.
                          example: 500.25
                        demand:
                          type: number
                          format: float
                          description: Demanda energética en kW.
                          example: 200.75
                        cost:
                          type: number
                          format: float
                          description: Costo asociado al consumo energético.
                          example: 150.50
                        totalCost:
                          type: number
                          format: float
                          description: Costo total del consumo energético.
                          example: 1000.00
        400:
          description: Parámetros inválidos o faltantes.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Missing required parameters: period or siteId"
        500:
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"
